apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  selector:
    app.kubernetes.io/name: edge-receiver
ports:
  - port:  1883
    targetPort:  default
    protocol:  TCP
    name:  mqtt
  - port:  11883
    targetPort:  default
    protocol:  TCP
    name:  mqtt-2
  - port:  80
    targetPort:  websocket
    protocol:  TCP
    name:  websocket
  - port: 443
    targetPort: default
    protocol: TCP
    name: https