apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app.kubernetes.io/name: edge-receiver
ports:
  - port:  1883
    targetPort:  default
    protocol:  TCP
    name:  default
  - port:  8080
    targetPort:  websocket
    protocol:  TCP
    name:  websocket
  - port: 443
    targetPort: default
    protocol: TCP
    name: https